# Generated by Django 4.2.6 on 2023-12-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.IntegerField(verbose_name='Fonte')),
                ('desc_fonte', models.CharField(max_length=150, verbose_name='Descrição da fonte')),
            ],
        ),
        migrations.AlterField(
            model_name='processos',
            name='valor_ind',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Indicação'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='valor_solicitado_ind',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Solicitado'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.fonte'),
        ),
    ]
