# Generated by Django 4.2.6 on 2023-12-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_fonte_alter_processos_valor_ind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processos',
            old_name='fonte',
            new_name='fonte2',
        ),
    ]
