# Generated by Django 4.2.6 on 2023-12-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_rename_fonte_processos_fonte2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='fonte2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.fonte', verbose_name='Fonte'),
        ),
    ]
