# Generated by Django 4.2.6 on 2023-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_fonte_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonte',
            name='fonte',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='ano_da_indicação',
            field=models.DateField(help_text='Insira a data neste formato: <em>DD-MM-YYYY</em>.'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='contrato',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contrato'),
        ),
    ]
