# Generated by Django 4.2.6 on 2023-12-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_fonte_fonte_alter_processos_ano_da_indicação_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='contrato',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contrato'),
        ),
    ]
