# Generated by Django 4.2.6 on 2023-12-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_processos_processo_processos_processo_do_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paoe', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='PAOE')),
                ('desc_paoe', models.CharField(max_length=150, verbose_name='Descrição da PAOE')),
            ],
        ),
        migrations.AlterField(
            model_name='processos',
            name='valor_ind',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor da Indicação'),
        ),
        migrations.AddField(
            model_name='processos',
            name='paoe2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.paoe', verbose_name='PAOE'),
        ),
    ]
