# Generated by Django 4.2.6 on 2023-12-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_paoe_alter_processos_valor_ind_processos_paoe2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='paoe2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastro.paoe', verbose_name='PAOE'),
            preserve_default=False,
        ),
    ]
