# Generated by Django 4.2.6 on 2023-12-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_processos_paoe2'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fonte',
            constraint=models.UniqueConstraint(fields=('fonte', 'desc_fonte'), name='fonte repetida'),
        ),
        migrations.AddConstraint(
            model_name='paoe',
            constraint=models.UniqueConstraint(fields=('paoe', 'desc_paoe'), name='paoe repetida'),
        ),
    ]
