# Generated by Django 4.2.6 on 2023-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_fonte_fonte_repetida_paoe_paoe_repetida'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fonte',
            name='fonte repetida',
        ),
        migrations.RemoveConstraint(
            model_name='paoe',
            name='paoe repetida',
        ),
        migrations.AddConstraint(
            model_name='fonte',
            constraint=models.UniqueConstraint(fields=('fonte',), name='fonte repetida'),
        ),
        migrations.AddConstraint(
            model_name='paoe',
            constraint=models.UniqueConstraint(fields=('paoe',), name='paoe repetida'),
        ),
    ]
