# Generated by Django 4.2.6 on 2023-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_remove_fonte_fonte_repetida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paoe',
            name='paoe',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='PAOE'),
        ),
    ]
