# Generated by Django 4.2.6 on 2023-12-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_paoe_paoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paoe',
            name='paoe',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='PAOE'),
        ),
    ]
