# Generated by Django 4.2.6 on 2024-01-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_paoe_paoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paoe',
            name='paoe',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='PAOE'),
        ),
    ]
