# Generated by Django 5.0 on 2024-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_alter_paoe_paoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150, verbose_name='ITEM')),
                ('desc_item', models.CharField(max_length=150, verbose_name='Descrição da Item')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pta',
            constraint=models.UniqueConstraint(fields=('item',), name='item repetida'),
        ),
    ]
