# Generated by Django 5.0 on 2024-01-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_pta_pta_item_repetida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pta',
        ),
    ]
