# Generated by Django 4.2.6 on 2024-02-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_delete_pta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='ano_da_indicação',
            field=models.DateField(help_text='Insira a data neste formato: <em>DD-MM-YYYY</em>.', unique_for_year=True),
        ),
    ]
