# Generated by Django 4.2.6 on 2024-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_alter_processos_ano_da_indicação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='valor_solicitado_ind',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Solicitado'),
        ),
    ]
