# Generated by Django 4.2.6 on 2024-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_remove_processos_processo_do_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paoe',
            name='paoe',
            field=models.IntegerField(verbose_name='PAOE'),
        ),
    ]
