# Generated by Django 4.2.6 on 2024-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_alter_paoe_paoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paoe',
            name='paoe',
            field=models.CharField(max_length=4, verbose_name='PAOE'),
        ),
    ]
