# Generated by Django 4.2.6 on 2024-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_alter_paoe_paoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_unidade', models.CharField(help_text='1º BBM', max_length=30, verbose_name='Silga da Unidade')),
                ('localidade', models.CharField(help_text='Salvador', max_length=30, verbose_name='Localidade')),
            ],
        ),
        migrations.AlterField(
            model_name='paoe',
            name='paoe',
            field=models.CharField(max_length=150, verbose_name='PAOE'),
        ),
    ]
