# Generated by Django 4.2.6 on 2024-03-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_bbm_alter_paoe_paoe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processos',
            name='processo do ano',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='bbm',
        ),
        migrations.AddField(
            model_name='processos',
            name='bbm2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='cadastro.bbm', verbose_name='BBM'),
        ),
        migrations.AddConstraint(
            model_name='processos',
            constraint=models.UniqueConstraint(fields=('processo', 'ano_da_indicação', 'fonte2', 'paoe2', 'bbm2'), name='processo do ano'),
        ),
    ]
