# Generated by Django 4.2.6 on 2024-03-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_bbm_desc_unidade_alter_bbm_sigla_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=30, verbose_name='Elemento')),
            ],
        ),
        migrations.AlterField(
            model_name='bbm',
            name='desc_unidade',
            field=models.CharField(default='', help_text='Nome por extenso da unidade.', max_length=50, verbose_name='Descrição da Unidade'),
        ),
        migrations.AlterField(
            model_name='bbm',
            name='localidade',
            field=models.CharField(help_text='Localidade em que a UBM está situada.', max_length=30, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='bbm',
            name='sigla_unidade',
            field=models.CharField(help_text='Exemplo: <strong>SCG</strong>.', max_length=12, verbose_name='Sigla da Unidade'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='bbm2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.bbm', verbose_name='BBM'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.elemento', verbose_name='Elemento'),
        ),
    ]
