# Generated by Django 4.2.6 on 2024-03-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_elemento_alter_bbm_desc_unidade_alter_bbm_localidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='elemento',
        ),
        migrations.AddField(
            model_name='elemento',
            name='desc_elemento',
            field=models.CharField(default='', max_length=250, verbose_name='Descrição do elemento'),
        ),
        migrations.AddField(
            model_name='processos',
            name='elemento2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='cadastro.elemento', verbose_name='Elemento'),
        ),
    ]
