# Generated by Django 4.2.6 on 2024-03-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0028_remove_processos_elemento_elemento_desc_elemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='desc_elemento',
            field=models.CharField(max_length=250, verbose_name='Descrição do elemento'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='elemento2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.elemento', verbose_name='Elemento'),
        ),
    ]
