# Generated by Django 4.2.6 on 2024-03-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0029_alter_elemento_desc_elemento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processos',
            old_name='ano_da_indicação',
            new_name='data_da_indicação',
        ),
    ]
