# Generated by Django 4.2.6 on 2024-04-03 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0030_rename_ano_da_indicação_processos_data_da_indicação'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processos',
            name='processo do ano',
        ),
        migrations.AddField(
            model_name='processos',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='processos',
            constraint=models.UniqueConstraint(fields=('processo', 'data_da_indicação', 'fonte2', 'paoe2', 'bbm2'), name='processo do ano'),
        ),
    ]
