# Generated by Django 4.2.6 on 2024-04-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0032_alter_processos_elemento2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processos',
            name='processo do ano',
        ),
    ]
