# Generated by Django 4.2.6 on 2024-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0033_remove_processos_processo_do_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='data_da_indicação',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
