# Generated by Django 4.2.6 on 2024-04-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0034_alter_processos_data_da_indicação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='valor_ind',
            field=models.DecimalField(decimal_places=4, max_digits=100, verbose_name='Valor da Indicação'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='valor_solicitado_ind',
            field=models.DecimalField(decimal_places=4, max_digits=100, verbose_name='Valor Solicitado'),
        ),
    ]
