# Generated by Django 4.2.6 on 2024-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0037_alter_processos_valor_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='valor_solicitado_ind',
            field=models.CharField(max_length=2000, verbose_name='Valor Solicitado'),
        ),
    ]
