# Generated by Django 4.2.6 on 2024-05-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0038_alter_processos_valor_solicitado_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='valor_ind',
            field=models.CharField(default='R$0,00', max_length=2000, verbose_name='Valor da Indicação'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='valor_solicitado_ind',
            field=models.CharField(default='R$0,00', max_length=2000, verbose_name='Valor Solicitado'),
        ),
    ]
