# Generated by Django 4.2.6 on 2024-06-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0040_alter_processos_data_da_indicação'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeGestora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ug', models.IntegerField(null=True, verbose_name='Número da UG')),
                ('gestora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.bbm', verbose_name='Nome da Gestora:')),
            ],
        ),
        migrations.RemoveField(
            model_name='processos',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='data_da_indicação',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='valor_ind',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='valor_solicitado_ind',
        ),
        migrations.AddField(
            model_name='processos',
            name='data_da_solicitacao',
            field=models.DateField(verbose_name='Data da Solicitação'),
        ),
        migrations.AddField(
            model_name='processos',
            name='valor_solicitado',
            field=models.CharField(blank=True, default='R$0,00', max_length=2000, null=True, unique=True, verbose_name='Valor Solicitado'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='bbm2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.bbm', verbose_name='OBM'),
        ),
        migrations.DeleteModel(
            name='Campo',
        ),
        migrations.AddField(
            model_name='processos',
            name='ug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.unidadegestora', verbose_name='Unidade Geradora'),
        ),
    ]
