# Generated by Django 4.2.6 on 2024-06-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0041_unidadegestora_remove_processos_campo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='data_da_solicitacao',
            field=models.DateField(null=True, verbose_name='Data da Solicitação'),
        ),
    ]
