# Generated by Django 4.2.6 on 2024-06-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0044_alter_processos_data_da_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='ug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.unidadegestora', verbose_name='Unidade Geradora'),
        ),
    ]
