# Generated by Django 4.2.6 on 2024-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0045_alter_processos_ug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='data_da_solicitacao',
            field=models.DateField(default='', verbose_name='Data da Solicitação'),
        ),
    ]
