# Generated by Django 4.2.6 on 2024-06-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0048_alter_processos_data_da_solicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='data_da_solicitacao',
        ),
    ]
