# Generated by Django 4.2.6 on 2024-06-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0049_remove_processos_data_da_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='data_da_solicitacao',
            field=models.DateField(null=True, verbose_name='Data da Solicitação'),
        ),
    ]
